name: build
on:
  push:

defaults:
  run:
    shell: bash -euo pipefail -c "source nix.source && exec bash {0}"

jobs:
  linux:
    runs-on: digital-asset-dpm
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 #v6.0.3
      - uses: ./.github/actions/nix

      - name: Run go build
        run: go build -o target/ ./cmd/...

      - name: Run Go tests and generate in json format
        run: go test -json -v ./... | tee report.json; exit ${PIPESTATUS[0]}

      - name: Check for stale generated docs
        run: make check-stale-docs

      - name: Publish Test Report
        uses: dorny/test-reporter@fe45e9537387dac839af0d33ba56eed8e24189e8
        with:
          name: Go Tests
          path: report.json
          reporter: golang-json
          fail-on-error: 'true'
          fail-on-empty: 'true'
          report-title: 'Go Tests'
      - name: Run manual installation
        run: docs/src/public/manual-install.sh
      - uses: ./.github/actions/nsis
        with:
          bin-path: target/dpm

  windows:
    runs-on: windows-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 #v6.0.3
      - uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
        with:
          go-version: '1.23.5'
      - name: Check
        run: |
            go mod tidy
            git diff --exit-code --color go.mod go.sum || {
              echo "::error::Please run 'go mod tidy'"
              exit 1
            }
        shell: bash
      - run: go build -o target/ ./cmd/...
        shell: bash
      - name: Run Go tests and generate in json format
        run: go test -json -v ./... | tee report.json; exit ${PIPESTATUS[0]}
        shell: bash
      - name: Publish Test Report
        uses: dorny/test-reporter@fe45e9537387dac839af0d33ba56eed8e24189e8
        with:
          name: Go Tests
          path: report.json
          reporter: golang-json

  release-public:
    runs-on: digital-asset-dpm
    needs: 
      - windows
      - linux
    if: success() && startsWith(github.ref, 'refs/tags/') && github.ref != 'refs/tags/0.0.0-skiprelease'
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 #v6.0.3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/release
        with:
          # todo - update once decided moved to CF
          repo: "temp"
          flags: "--clean --skip=announce,publish,validate"
          gh_token: ${{ secrets.GITHUB_TOKEN }}

  release-public-unstable:
    runs-on: digital-asset-dpm
    needs: 
      - windows
      - linux
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 #v6.0.3
      - uses: ./.github/actions/release
        with:
          # todo - update once decided moved to CF
          repo: "temp/temp"
          flags: "--snapshot"
          gh_token: ${{ secrets.GITHUB_TOKEN }}
